1:
  blacklists:
    - name: Frankfurt
      flag: ðŸ‡©ðŸ‡ª
      ip: 77.221.157.159
      port: 443
      sni: web.max.ru
      pbk: z8Q2qDZKKP2rNNxanKtULLFaEfe4tQQjhvDQeRlkxww
    - name: Charlotte
      flag: ðŸ‡ºðŸ‡¸
      ip: 62.60.176.107
      port: 443
      sni: web.max.ru
      pbk: 9KqBe_8dFdOquT0fbcr4lgAAOOgPL1qH1OW4xHQZKQU