ru:
  general:
    - name: Frankfurt
      country_code: de1
      flag: ðŸ‡©ðŸ‡ª
      ip: 77.221.157.159
      port: 443
      sni: web.max.ru
      public_key: z8Q2qDZKKP2rNNxanKtULLFaEfe4tQQjhvDQeRlkxww
  fallback:
    - name: Frankfurt
      country_code: de1
      flag: ðŸ‡©ðŸ‡ª
      ip: 77.221.157.159
      port: 443
      sni: web.max.ru
      public_key: z8Q2qDZKKP2rNNxanKtULLFaEfe4tQQjhvDQeRlkxww

ruwh:
  general:
    - name: Whitelist (TEST)
      country_code: wl1
      flag: ðŸ‡·ðŸ‡º
      ip: 62.60.229.169
      port: 443
      sni: web.max.ru
      public_key: EolrHtHwjs7wVBHVVFIkfQdrckkL5ByKL5948UHA8GQ
  fallback:
    - name: Frankfurt
      country_code: de1
      flag: ðŸ‡©ðŸ‡ª
      ip: 77.221.157.159
      port: 443
      sni: web.max.ru
      public_key: z8Q2qDZKKP2rNNxanKtULLFaEfe4tQQjhvDQeRlkxww=