services:
  thebeyond-db:
    container_name: thebeyond-db
    image: postgres:18.0-alpine3.22
    restart: always
    shm_size: 128mb
    ports:
      - "${POSTGRES_PORT:-4568}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-thebeyond}
      PGDATA: /data/postgres
    volumes:
      - ${DATA_PATH:-./data}:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-thebeyond}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - default
      - thebeyond-network

  thebeyond-migrator:
    build:
      context: .
      dockerfile: ./Dockerfile.migrator
    container_name: thebeyond-migrator
    command: migrate run --source /migrations
    restart: no
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD}@thebeyond-db:5432/${POSTGRES_DB:-thebeyond}
    volumes:
      - ${MIGRATIONS_PATH:-./migrations}:/migrations:ro
    depends_on:
      thebeyond-db:
        condition: service_healthy
    networks:
      - default
      - thebeyond-network

  thebeyond-bot:
    container_name: thebeyond-bot
    image: ${REGISTRY:-cr.yandex}/${YC_REGISTRY_NAME:-crpon6vsi4chaca55ctd}/${PROJECT_NAME:-thebeyond}-bot:${TAG:-latest}
    restart: always
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD}@thebeyond-db:5432/${POSTGRES_DB:-thebeyond}
      SUBSCRIPTIONS_PATH: /etc/thebeyond/subscriptions/subscriptions.yaml
      CLUSTERS_PATH: /etc/thebeyond/xray/clusters.yaml
      HOWTOUSE_INSTRUCTION_PATH: /shared/assets/instruction.png
      PROJECT_AVATAR_PATH: /shared/assets/avatar.png
      WELCOME_PREVIEW_PATH: /shared/assets/welcome.png
    volumes:
      - ./configs:/etc/thebeyond:rw
      - ./assets:/shared/assets:rw
    depends_on:
      thebeyond-db:
        condition: service_healthy
      thebeyond-migrator:
        condition: service_completed_successfully
    networks:
      - default
      - thebeyond-network

  thebeyond-api:
    container_name: thebeyond-api
    image: ${REGISTRY:-cr.yandex}/${YC_REGISTRY_NAME:-crpon6vsi4chaca55ctd}/${PROJECT_NAME:-thebeyond}-api:${TAG:-latest}
    restart: always
    ports:
      - "2083:2083"
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD}@thebeyond-db:5432/${POSTGRES_DB:-thebeyond}
      SUBSCRIPTIONS_PATH: /etc/thebeyond/subscriptions/subscriptions.yaml
      CLUSTERS_PATH: /etc/thebeyond/xray/clusters.yaml
    volumes:
      - ./configs:/etc/thebeyond:rw
    depends_on:
      thebeyond-db:
        condition: service_healthy
      thebeyond-migrator:
        condition: service_completed_successfully
    networks:
      - default
      - thebeyond-network
  # thebeyond-gateway:
  #   container_name: thebeyond-gateway
  #   image: nginx:1.29-alpine3.22
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - D:/etc/thebeyond/nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  thebeyond-network:
    external: true
