services:
  thebeyond-db:
    container_name: thebeyond-db
    image: postgres:18.0-alpine3.22
    restart: always
    shm_size: 128mb
    ports:
      - "${POSTGRES_PORT:-4568}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-thebeyond}
      PGDATA: /data/postgres
    volumes:
      - ${DATA_PATH:-./data}:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-thebeyond}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - default
      - thebeyond-network

  thebeyond-migrator:
    build:
      context: .
      dockerfile: ./Dockerfile.migrator
    container_name: thebeyond-migrator
    command: migrate run --source /migrations
    restart: no
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD}@thebeyond-db:5432/${POSTGRES_DB:-thebeyond}
    volumes:
      - ${MIGRATIONS_PATH:-./migrations}:/migrations:ro
    depends_on:
      thebeyond-db:
        condition: service_healthy
    networks:
      - default
      - thebeyond-network

  thebeyond-bot:
    container_name: thebeyond-bot
    image: ${REGISTRY:-cr.yandex}/${YC_REGISTRY_NAME:-crpon6vsi4chaca55ctd}/${PROJECT_NAME:-thebeyond}-bot:${TAG:-latest}
    restart: always
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      PROJECT_DOMAIN: ${PROJECT_DOMAIN:-example.com}
      DATABASE_URL: postgres://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD}@thebeyond-db:5432/${POSTGRES_DB:-thebeyond}
      SUBSCRIPTIONS_PATH: /etc/thebeyond/subscriptions/subscriptions.yaml
      CLUSTERS_PATH: /etc/thebeyond/xray/clusters.yaml
      ABOUT_IMAGE_PATH: /shared/assets/about.png
      MENU_IMAGE_PATH: /shared/assets/menu.png
      CONFIG_IMAGE_PATH: /shared/assets/config.png
    volumes:
      - ./configs:/etc/thebeyond:rw
      - ./assets:/shared/assets:rw
    depends_on:
      thebeyond-db:
        condition: service_healthy
      thebeyond-migrator:
        condition: service_completed_successfully
    networks:
      - default
      - thebeyond-network

  thebeyond-api:
    container_name: thebeyond-api
    image: ${REGISTRY:-cr.yandex}/${YC_REGISTRY_NAME:-crpon6vsi4chaca55ctd}/${PROJECT_NAME:-thebeyond}-api:${TAG:-latest}
    restart: always
    ports:
      - "8443:8443"
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      PORT: 8443
      DATABASE_URL: postgres://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD}@thebeyond-db:5432/${POSTGRES_DB:-thebeyond}
      SUBSCRIPTIONS_PATH: /etc/thebeyond/subscriptions/subscriptions.yaml
      CLUSTERS_PATH: /etc/thebeyond/xray/clusters.yaml
      CERT_FILE: /etc/ssl/certs/certificate.crt
      CERT_KEY_FILE: /etc/ssl/private/certificate.key
    volumes:
      - ./configs:/etc/thebeyond:rw
      - ./certificate.crt:/etc/ssl/certs/certificate.crt
      - ./certificate.key:/etc/ssl/private/certificate.key
    depends_on:
      thebeyond-db:
        condition: service_healthy
      thebeyond-migrator:
        condition: service_completed_successfully
    networks:
      - default
      - thebeyond-network

networks:
  thebeyond-network:
    external: true
