7:
    emoji: "\U0001F37F"
    prices:
        aed: 2.03
        bdt: 67.47
        bgn: 0.92
        brl: 2.99
        cad: 0.76
        cny: 3.89
        czk: 11.41
        dkk: 3.51
        eur: 0.47
        gbp: 0.41
        huf: 181.05
        idr: 9179.48
        ils: 1.78
        inr: 49.99
        irr: 23182.6
        jpy: 86.02
        krw: 814.04
        mxn: 9.94
        myr: 2.26
        nok: 5.6
        php: 32.63
        pkr: 154.81
        pln: 1.99
        ron: 2.39
        rsd: 55.21
        rub: 44
        sar: 2.07
        sek: 5.12
        sgd: 0.71
        stars: 24
        thb: 17.39
        try: 23.57
        uah: 23.32
        usd: 0.55
        vnd: 14524.92
    discount: 0
14:
    emoji: "\U0001F496"
    prices:
        aed: 4.05
        bdt: 134.93
        bgn: 1.84
        brl: 5.97
        cad: 1.52
        cny: 7.79
        czk: 22.82
        dkk: 7.02
        eur: 0.94
        gbp: 0.83
        huf: 362.1
        idr: 18358.95
        ils: 3.55
        inr: 99.97
        irr: 46365.19
        jpy: 172.03
        krw: 1628.09
        mxn: 19.88
        myr: 4.52
        nok: 11.19
        php: 65.27
        pkr: 309.62
        pln: 3.97
        ron: 4.79
        rsd: 110.42
        rub: 88
        sar: 4.14
        sek: 10.23
        sgd: 1.43
        stars: 48
        thb: 34.79
        try: 47.14
        uah: 46.64
        usd: 1.1
        vnd: 29049.84
    discount: 0
30:
    emoji: "\U0001F315"
    prices:
        aed: 8.25
        bdt: 274.47
        bgn: 3.74
        brl: 12.15
        cad: 3.09
        cny: 15.84
        czk: 46.41
        dkk: 14.29
        eur: 1.91
        gbp: 1.68
        huf: 736.54
        idr: 37343.78
        ils: 7.23
        inr: 203.35
        irr: 94311.01
        jpy: 349.93
        krw: 3311.67
        mxn: 40.43
        myr: 9.2
        nok: 22.77
        php: 132.76
        pkr: 629.79
        pln: 8.08
        ron: 9.74
        rsd: 224.6
        rub: 179
        sar: 8.42
        sek: 20.82
        sgd: 2.9
        stars: 100.00000000000001
        thb: 70.76
        try: 95.88
        uah: 94.88
        usd: 2.25
        vnd: 59090.01
    discount: 0
90:
    emoji: "\U0001F337"
    prices:
        aed: 19.54
        bdt: 650.14
        bgn: 8.86
        brl: 28.78
        cad: 7.33
        cny: 37.53
        czk: 109.94
        dkk: 33.84
        eur: 4.53
        gbp: 3.98
        huf: 1744.65
        idr: 88456.77
        ils: 17.13
        inr: 481.68
        irr: 223395.92
        jpy: 828.88
        krw: 7844.41
        mxn: 95.77
        myr: 21.8
        nok: 53.92
        php: 314.47
        pkr: 1491.79
        pln: 19.15
        ron: 23.07
        rsd: 532.01
        rub: 424
        sar: 19.95
        sek: 49.31
        sgd: 6.87
        stars: 250
        thb: 167.61
        try: 227.12
        uah: 224.74
        usd: 5.32
        vnd: 139967.41
    discount: 0
180:
    emoji: "\U0001F308"
    prices:
        aed: 38.2
        bdt: 1271.15
        bgn: 17.33
        brl: 56.26
        cad: 14.33
        cny: 73.37
        czk: 214.95
        dkk: 66.17
        eur: 8.86
        gbp: 7.78
        huf: 3411.12
        idr: 172949.67
        ils: 33.48
        inr: 941.78
        irr: 436781.17
        jpy: 1620.61
        krw: 15337.31
        mxn: 187.25
        myr: 42.62
        nok: 105.43
        php: 614.84
        pkr: 2916.74
        pln: 37.43
        ron: 45.1
        rsd: 1040.18
        rub: 829
        sar: 39
        sek: 96.4
        sgd: 13.44
        stars: 500
        thb: 327.7
        try: 444.06
        uah: 439.4
        usd: 10.4
        vnd: 273662.69
    discount: 0
365:
    emoji: ⭐️
    prices:
        aed: 75.98
        bdt: 2528.49
        bgn: 34.47
        brl: 111.92
        cad: 28.5
        cny: 145.95
        czk: 427.57
        dkk: 131.61
        eur: 17.63
        gbp: 15.47
        huf: 6785.2
        idr: 344021.72
        ils: 66.6
        inr: 1873.34
        irr: 868820.44
        jpy: 3223.63
        krw: 30508.11
        mxn: 372.46
        myr: 84.77
        nok: 209.72
        php: 1223.01
        pkr: 5801.81
        pln: 74.46
        ron: 89.7
        rsd: 2069.06
        rub: 1649
        sar: 77.58
        sek: 191.76
        sgd: 26.72
        stars: 1000
        thb: 651.85
        try: 883.31
        uah: 874.04
        usd: 20.69
        vnd: 544354.37
    discount: 0
