7:
    emoji: "\U0001F37F"
    prices:
        aed: 2.11
        bdt: 70.42
        bgn: 0.97
        brl: 3.12
        cad: 0.8
        cny: 4.07
        czk: 11.96
        dkk: 3.69
        eur: 0.49
        gbp: 0.43
        huf: 188.73
        idr: 9589.04
        ils: 1.86
        inr: 51.86
        irr: 24207.58
        jpy: 89.44
        krw: 846.72
        mxn: 10.46
        myr: 2.37
        nok: 5.82
        php: 33.95
        pkr: 161.56
        pln: 2.09
        ron: 2.52
        rsd: 58.06
        rub: 44
        sar: 2.16
        sek: 5.41
        sgd: 0.75
        stars: 24
        thb: 18.37
        try: 24.49
        uah: 24.25
        usd: 0.58
        vnd: 15182.75
    discount: 0
14:
    emoji: "\U0001F496"
    prices:
        aed: 4.23
        bdt: 140.84
        bgn: 1.93
        brl: 6.24
        cad: 1.59
        cny: 8.14
        czk: 23.93
        dkk: 7.39
        eur: 0.99
        gbp: 0.86
        huf: 377.46
        idr: 19178.09
        ils: 3.72
        inr: 103.72
        irr: 48415.15
        jpy: 178.87
        krw: 1693.45
        mxn: 20.93
        myr: 4.74
        nok: 11.64
        php: 67.9
        pkr: 323.12
        pln: 4.18
        ron: 5.04
        rsd: 116.11
        rub: 88
        sar: 4.32
        sek: 10.83
        sgd: 1.49
        stars: 48
        thb: 36.75
        try: 48.98
        uah: 48.5
        usd: 1.15
        vnd: 30365.5
    discount: 0
30:
    emoji: "\U0001F315"
    prices:
        aed: 8.6
        bdt: 286.48
        bgn: 3.93
        brl: 12.7
        cad: 3.24
        cny: 16.56
        czk: 48.67
        dkk: 15.02
        eur: 2.01
        gbp: 1.76
        huf: 767.78
        idr: 39009.97
        ils: 7.57
        inr: 210.98
        irr: 98480.82
        jpy: 363.85
        krw: 3444.63
        mxn: 42.57
        myr: 9.63
        nok: 23.68
        php: 138.12
        pkr: 657.26
        pln: 8.51
        ron: 10.24
        rsd: 236.18
        rub: 179
        sar: 8.78
        sek: 22.03
        sgd: 3.03
        stars: 100.00000000000001
        thb: 74.75
        try: 99.64
        uah: 98.65
        usd: 2.34
        vnd: 61766.18
    discount: 0
90:
    emoji: "\U0001F337"
    prices:
        aed: 20.37
        bdt: 678.59
        bgn: 9.32
        brl: 30.09
        cad: 7.67
        cny: 39.23
        czk: 115.29
        dkk: 35.59
        eur: 4.77
        gbp: 4.16
        huf: 1818.65
        idr: 92403.5
        ils: 17.94
        inr: 499.76
        irr: 233273
        jpy: 861.85
        krw: 8159.34
        mxn: 100.84
        myr: 22.81
        nok: 56.08
        php: 327.16
        pkr: 1556.85
        pln: 20.15
        ron: 24.26
        rsd: 559.44
        rub: 424
        sar: 20.8
        sek: 52.17
        sgd: 7.19
        stars: 250
        thb: 177.05
        try: 236.02
        uah: 233.67
        usd: 5.55
        vnd: 146306.48
    discount: 0
180:
    emoji: "\U0001F308"
    prices:
        aed: 39.84
        bdt: 1326.76
        bgn: 18.22
        brl: 58.83
        cad: 14.99
        cny: 76.7
        czk: 225.4
        dkk: 69.58
        eur: 9.32
        gbp: 8.13
        huf: 3555.8
        idr: 180666.28
        ils: 35.07
        inr: 977.13
        irr: 456092.74
        jpy: 1685.08
        krw: 15953.06
        mxn: 197.16
        myr: 44.61
        nok: 109.65
        php: 639.66
        pkr: 3043.94
        pln: 39.4
        ron: 47.44
        rsd: 1093.82
        rub: 829
        sar: 40.68
        sek: 102
        sgd: 14.05
        stars: 500
        thb: 346.17
        try: 461.46
        uah: 456.87
        usd: 10.85
        vnd: 286056.78
    discount: 0
365:
    emoji: ⭐️
    prices:
        aed: 79.24
        bdt: 2639.12
        bgn: 36.25
        brl: 117.02
        cad: 29.82
        cny: 152.56
        czk: 448.36
        dkk: 138.4
        eur: 18.53
        gbp: 16.17
        huf: 7073.01
        idr: 359371.17
        ils: 69.77
        inr: 1943.65
        irr: 907233.93
        jpy: 3351.87
        krw: 31732.92
        mxn: 392.17
        myr: 88.73
        nok: 218.11
        php: 1272.38
        pkr: 6054.84
        pln: 78.38
        ron: 94.36
        rsd: 2175.76
        rub: 1649
        sar: 80.91
        sek: 202.9
        sgd: 27.96
        stars: 1000
        thb: 688.58
        try: 917.91
        uah: 908.79
        usd: 21.58
        vnd: 569008
    discount: 0
