7:
    emoji: "\U0001F37F"
    prices:
        aed: 2.1
        bdt: 70
        bgn: 0.96
        brl: 3.11
        cad: 0.79
        cny: 4.05
        czk: 11.89
        dkk: 3.67
        eur: 0.49
        gbp: 0.43
        huf: 187.68
        idr: 9548.82
        ils: 1.85
        inr: 51.48
        irr: 24091.44
        jpy: 88.69
        krw: 841.22
        mxn: 10.4
        myr: 2.35
        nok: 5.78
        php: 33.76
        pkr: 160.52
        pln: 2.08
        ron: 2.5
        rsd: 57.7
        rub: 44
        sar: 2.15
        sek: 5.38
        sgd: 0.74
        stars: 24
        thb: 18.27
        try: 24.37
        uah: 24.1
        usd: 0.57
        vnd: 15087.01
    discount: 0
14:
    emoji: "\U0001F496"
    prices:
        aed: 4.2
        bdt: 140.01
        bgn: 1.92
        brl: 6.23
        cad: 1.58
        cny: 8.09
        czk: 23.78
        dkk: 7.34
        eur: 0.98
        gbp: 0.86
        huf: 375.36
        idr: 19097.63
        ils: 3.7
        inr: 102.96
        irr: 48182.88
        jpy: 177.38
        krw: 1682.45
        mxn: 20.8
        myr: 4.71
        nok: 11.57
        php: 67.52
        pkr: 321.04
        pln: 4.16
        ron: 5
        rsd: 115.41
        rub: 88
        sar: 4.29
        sek: 10.75
        sgd: 1.48
        stars: 48
        thb: 36.53
        try: 48.74
        uah: 48.19
        usd: 1.14
        vnd: 30174.02
    discount: 0
30:
    emoji: "\U0001F315"
    prices:
        aed: 8.55
        bdt: 284.79
        bgn: 3.91
        brl: 12.67
        cad: 3.22
        cny: 16.46
        czk: 48.37
        dkk: 14.93
        eur: 2
        gbp: 1.75
        huf: 763.52
        idr: 38846.32
        ils: 7.53
        inr: 209.43
        irr: 98008.36
        jpy: 360.8
        krw: 3422.25
        mxn: 42.31
        myr: 9.58
        nok: 23.53
        php: 137.34
        pkr: 653.03
        pln: 8.45
        ron: 10.18
        rsd: 234.75
        rub: 179
        sar: 8.73
        sek: 21.87
        sgd: 3.02
        stars: 100.00000000000001
        thb: 74.31
        try: 99.15
        uah: 98.02
        usd: 2.33
        vnd: 61376.7
    discount: 0
90:
    emoji: "\U0001F337"
    prices:
        aed: 20.26
        bdt: 674.58
        bgn: 9.26
        brl: 30.02
        cad: 7.63
        cny: 39
        czk: 114.58
        dkk: 35.36
        eur: 4.73
        gbp: 4.14
        huf: 1808.57
        idr: 92015.87
        ils: 17.83
        inr: 496.08
        irr: 232153.88
        jpy: 854.64
        krw: 8106.35
        mxn: 100.23
        myr: 22.68
        nok: 55.73
        php: 325.33
        pkr: 1546.84
        pln: 20.02
        ron: 24.11
        rsd: 556.06
        rub: 424
        sar: 20.69
        sek: 51.8
        sgd: 7.15
        stars: 250
        thb: 176.03
        try: 234.86
        uah: 232.19
        usd: 5.52
        vnd: 145383.92
    discount: 0
180:
    emoji: "\U0001F308"
    prices:
        aed: 39.61
        bdt: 1318.93
        bgn: 18.1
        brl: 58.69
        cad: 14.91
        cny: 76.25
        czk: 224.03
        dkk: 69.14
        eur: 9.26
        gbp: 8.09
        huf: 3536.09
        idr: 179908.39
        ils: 34.86
        inr: 969.93
        irr: 453904.64
        jpy: 1670.99
        krw: 15849.44
        mxn: 195.97
        myr: 44.35
        nok: 108.97
        php: 636.08
        pkr: 3024.36
        pln: 39.15
        ron: 47.14
        rsd: 1087.21
        rub: 829
        sar: 40.45
        sek: 101.28
        sgd: 13.97
        stars: 500
        thb: 344.17
        try: 459.19
        uah: 453.97
        usd: 10.79
        vnd: 284253
    discount: 0
365:
    emoji: ⭐️
    prices:
        aed: 78.79
        bdt: 2623.55
        bgn: 36.01
        brl: 116.74
        cad: 29.66
        cny: 151.67
        czk: 445.63
        dkk: 137.52
        eur: 18.41
        gbp: 16.09
        huf: 7033.8
        idr: 357863.62
        ils: 69.34
        inr: 1929.33
        irr: 902881.49
        jpy: 3323.84
        krw: 31526.8
        mxn: 389.81
        myr: 88.21
        nok: 216.75
        php: 1265.26
        pkr: 6015.89
        pln: 77.88
        ron: 93.76
        rsd: 2162.62
        rub: 1649
        sar: 80.46
        sek: 201.45
        sgd: 27.79
        stars: 1000
        thb: 684.61
        try: 913.4
        uah: 903.02
        usd: 21.45
        vnd: 565420.03
    discount: 0
